POST http://localhost:8080/events
content-type: application/json

{
  "name": "Test Event 2",
  "description": "This is a test event 2",
  "location": "Test Location",
  "dateTime": "2021-12-31T23:59:59Z"
}

