POST http://localhost:8080/events/2/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzIiwiZXhwIjoxNzIyMTYwNzc2LCJ1c2VySWQiOjN9.-tKI2gTIbysHZatCAyaQzIdFxS2KFhwisH1Y-ZYxPUM
