POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QiLCJleHAiOjE3MjIwODM4MjMsInVzZXJJZCI6MX0.FSVC9NhrWwf83zDmQ_5BxeqNhDcze3FoQRqf7AkD4iE


{
  "name": "Test Event 4",
  "description": "This is a test event 3",
  "location": "Test Location",
  "dateTime": "2021-12-31T23:59:59Z"
}

