POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6MCwiZXhwIjoxNzIyMDc4NDYwLCJ1c2VySWQiOiJ0ZXN0In0.EpE649vWIT9bhVOfanpwn3wYh9klhmlwTZ99M8sDXj4

{
  "name": "Test Event 5",
  "description": "This is a test event 5",
  "location": "Test Location",
  "dateTime": "2021-12-31T23:59:59Z"
}

